package com.example.jamify.model

import android.graphics.Color
import android.net.Uri
import android.text.Spannable
import android.text.style.ForegroundColorSpan
import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import java.io.Serializable

// Firebase insists we have a no argument constructor
data class PostMeta(
    // Auth information
    var ownerName: String = "",
    var ownerUid: String = "",
    var photoUuid : String = "",
    var songTitle : String = "",
    var byteSize : Long = 0L,
    var caption: String = "",
    var songId : Long = 0L,
    var likes : List<String> = emptyList(),
    val private: Boolean = false,
    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // firestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
) : Serializable {

    fun searchForUser(userId: String): Boolean {
//        removeAllCurrentSpans()
        return ownerUid == userId

    }

    fun searchForSong(filterSong: String): Boolean {
        // which you determine by
//        removeAllCurrentSpans()
        return songTitle == filterSong

    }

}